/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calbul;

import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JTextField;

/**
 *
 * @author Pan-Kawia
 */
public class calendarInterface extends javax.swing.JPanel {

    public calendarInterface() {
        initComponents();
        TimeZoneList.fillComboBoxWithZone(timezoneCombo);
        timezoneCombo.setSelectedIndex(477);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        yearTex = new javax.swing.JTextField();
        longitudeTex = new javax.swing.JTextField();
        latitudeTex = new javax.swing.JTextField();
        timezoneCombo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        genCalendarBut = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        viewerButton = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(358, 206));

        jLabel1.setText("Rok:");

        jLabel2.setText("Długość geograficzna (λ):");

        jLabel3.setText("Szerokość geograficzna (φ):");

        yearTex.setText("2017");
        yearTex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearTexActionPerformed(evt);
            }
        });

        longitudeTex.setText("49.6090523");
        longitudeTex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                longitudeTexActionPerformed(evt);
            }
        });

        latitudeTex.setText("20.7037968");

        jLabel4.setText("Strefa czasowa:");

        genCalendarBut.setText("Generuj kalendarz");
        genCalendarBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genCalendarButActionPerformed(evt);
            }
        });

        jLabel5.setText("Wypełnij poniższy formularz:");

        viewerButton.setText("Podgląd");
        viewerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewerButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(viewerButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(genCalendarBut))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE))
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(yearTex, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(longitudeTex, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                                    .addComponent(latitudeTex, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(timezoneCombo, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(yearTex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(longitudeTex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(latitudeTex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(timezoneCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genCalendarBut)
                    .addComponent(viewerButton))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void yearTexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearTexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearTexActionPerformed

    private void genCalendarButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genCalendarButActionPerformed
        Calbul.setLatitude(getLatitudeTex());
        Calbul.setLongitude(getLongitudeTex());
        
        String unFormattedTimezone = (String) timezoneCombo.getSelectedItem();
        String[] formattedTimezone = unFormattedTimezone.split(" ");
        Calbul.setTimezoneId(formattedTimezone[0]);
        Calbul.setTimezone(formattedTimezone[1]);
        try {
            new Calbul(getYearTex());
        } catch (IOException ex) {
            Logger.getLogger(calendarInterface.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_genCalendarButActionPerformed

    private void longitudeTexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_longitudeTexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_longitudeTexActionPerformed

    private void viewerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewerButtonActionPerformed
            if(Desktop.isDesktopSupported()) {
            try {
                File myFile = new File("kalendarz.pdf");
                Desktop.getDesktop().open(myFile);
            } catch (IOException ex) {		        
            }
        }
		
    }//GEN-LAST:event_viewerButtonActionPerformed

    public String getLatitudeTex() {
        return latitudeTex.getText();
    }

    public String getLongitudeTex() {
        return longitudeTex.getText();
    }

    public String getTimezoneCombo() {
        return (String) timezoneCombo.getSelectedItem();
    }

    public String getYearTex() {
        return yearTex.getText();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton genCalendarBut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField latitudeTex;
    private javax.swing.JTextField longitudeTex;
    private javax.swing.JComboBox<String> timezoneCombo;
    private javax.swing.JButton viewerButton;
    private javax.swing.JTextField yearTex;
    // End of variables declaration//GEN-END:variables
}
